male(alex).
male(justin).
male(henry).
male(peter).
male(hector).
male(hamlet).
male(charles).
male(juan).
male(maurice).
male(leonardo).
female(valerie).
female(marena).
female(sandra).
female(maria).
female(rosa).
female(alexandra).
female(barbara).
female(virginia).
female(minerva).
female(gladys).
	